/* Enums */

export enum Electiontype {
  SCHULSPRECHER= 'SCHULSPRECHER',
  ABTEILUNGSSPRECHER = 'ABTEILUNGSSPRECHER',
  STICHWAHL_SCHULSPRECHER = 'STICHWAHL_SCHULSPRECHER',
  STICHWAHL_ABTEILUNGSSPRECHER = 'STICHWAHL_ABTEILUNGSSPRECHER'
}

export enum Electionstate {
  NEW,
  RUNNING,
  STOPPED,
  ENDED
}

export enum Department {
  INFORMATIK= 'INFORMATIK',
  MEDIENTECHNIK = 'MEDIENTECHNIK',
  ELEKTRONIK = 'ELEKTRONIK',
  MEDIZINTECHNIK = 'MEDIZINTECHNIK'
}
