
/* Enums */

export const enum Electiontype {
  SCHULSPRECHER = 'SCHULSPRECHER',
  ABTEILUNGSSPRECHER = 'ABTEILUNGSSPRECHER',
  STICHWAHL_SCHULSPRECHER = 'STICHWAHL_SCHULSPRECHER',
  STICHWAHL_ABTEILUNGSSPRECHER = 'STICHWAHL_ABTEILUNGSSPRECHER'
}

export const enum Electionstate {
  NEW = 'NEW',
  RUNNING = 'RUNNING',
  STOPPED = 'STOPPED',
  ENDED = 'ENDED'
}

export const enum Department {
  INFORMATIK= 'INFORMATIK',
  MEDIENTECHNIK = 'MEDIENTECHNIK',
  ELEKTRONIK = 'ELEKTRONIK',
  MEDIZINTECHNIK = 'MEDIZINTECHNIK',
  EMPTY = ''
}
